# Generated by Django 4.1.3 on 2024-10-10 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='description',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='tags',
            field=models.TextField(max_length=100, verbose_name=(('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low'))),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
