# Generated by Django 4.1.3 on 2024-10-10 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_username_user_user_alter_tasklist_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='tags',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=200, null=True),
        ),
    ]
