# Generated by Django 4.1.3 on 2024-10-10 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_tasklist_description_alter_tasklist_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='description',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
