# Generated by Django 4.1.3 on 2024-10-10 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_tasklist_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasklist',
            old_name='task',
            new_name='user',
        ),
    ]
