# Generated by Django 4.2.16 on 2024-10-16 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_tasklist_user_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
